config/routes.rb
Rails.application.routes.draw do
  resources :chats, only: [:show, :create]
  get 'users/:id/favorites' => 'users#favorites'
  get 'genres/show/:genre_id', to: 'genres#show', as: 'genre'
  get 'searches/search'
  devise_for :users
  root to: 'homes#top'
  get 'homes/top'
  get 'homes/about'

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as:  'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  resources :notifications, only: :index

  get '/search', to: 'searches#search'

end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  before_action :authenticate_user!

  def create
    current_user.follow(params[:user_id])
    @user = User.find(params[:user_id])
    @user.create_notification_follow!(current_user)
  end

  def destroy
    current_user.unfollow(params[:user_id])
    @user = User.find(params[:user_id])
  end

  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end

end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_count.html.erb
<div class= "mt-4">
  Follows： <%= link_to user.followings.count, user_followings_path(user) %>
</div>
<div class= "mt-2">
  Followers: <%= link_to user.followers.count, user_followers_path(user) %>
</div>

app/views/relationships/_follow-btn.html.erb
<% if current_user.following?(user) %>
  <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, remote: true, class: "btn btn-info" %>
<% else %>
  <%= link_to "フォローする", user_relationships_path(user.id), method: :post, remote: true, class: "btn btn-success" %>
<% end %>

app/views/relationships/create.js.erb
$(".follows-count").html("<%= j(render 'relationships/count', user: @user) %>");
$(".follow-btn").html("<%= j(render 'relationships/follow-btn', user: @user) %>");
$(".chat-btn").html("<%= j(render 'chats/chat-btn', user: @user) %>");

app/views/relationships/destroy.js.erb
$(".follows-count").html("<%= j(render 'relationships/count', user: @user) %>");
$(".follow-btn").html("<%= j(render 'relationships/follow-btn', user: @user) %>");
$(".chat-btn").html("<%= j(render 'chats/chat-btn', user: @user) %>");

app/views/relationships/followers.html.erb
<div class= "container">
  <div class= "row">
    <div class= "col-12 border-bottom">
      <h2 class= "pt-4 text-secondary text-center font-weight-bold"><%= current_user.name %>さんのフォロワー一覧</h2>
    </div>
    <% if @users.exists? %>
      <%= render 'users/users', users: @users %>
    <% else %>
      <h4 class= "mx-auto mt-4">ユーザーはいません</h4>
    <% end %>
  </div>
</div>

app/views/relationships/followings.html.erb
<div class= "container">
  <div class= "row">
    <div class= "col-12 border-bottom">
      <h2 class= "pt-4 text-secondary text-center font-weight-bold"><%= current_user.name %>さんがフォローしているユーザー一覧</h2>
    </div>
    <% if @users.exists? %>
      <%= render 'users/users', users: @users %>
    <% else %>
      <h4 class= "mx-auto mt-4">ユーザーはいません</h4>
    <% end %>
  </div>
</div>