config/routes.rb
Rails.application.routes.draw do
  resources :chats, only: [:show, :create]
  get 'users/:id/favorites' => 'users#favorites'
  get 'genres/show/:genre_id', to: 'genres#show', as: 'genre'
  get 'searches/search'
  devise_for :users
  root to: 'homes#top'
  get 'homes/top'
  get 'homes/about'

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as:  'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  resources :notifications, only: :index

  get '/search', to: 'searches#search'

end

app/models/notification.rb
class Notification < ApplicationRecord
  default_scope -> {order(created_at: :desc)}
  # nilを許可するための"optional: true"の記述
  belongs_to :post, optional: true
  belongs_to :comment, optional: true

  belongs_to :visitor, class_name: 'User', foreign_key: 'visitor_id', optional: true
  belongs_to :visited, class_name:'User', foreign_key: 'visited_id', optional: true
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController

  def index
    @notifications = current_user.passive_notifications.page(params[:page]).per(10)
    @notifications.where(checked: false).each do |notification|
      notification.update_attributes(checked: true)
    end
  end

end

app/helpers/notifications_helper.rb
module NotificationsHelper

  def unchecked_notifications
    @notifications = current_user.passive_notifications.where(checked: false)
  end

end

app/views/notifications/_notification.html.erb
<% visitor = notification.visitor %>
<% visited = notification.visited %>
<div class= "col-md-6 mx-auto mt-3">
  <div class= "border-bottom">
    <div>
      <%= link_to user_path(visitor) do %>
        <%= visitor.name %> さん
      <% end %>が
      <% case notification.action %>
      <% when 'follow' then %>
        <%= "あなたをフォローしました" %>
      <% when 'favorite' then %>
        <%= link_to 'あなたの投稿', notification.post %>
        <%= "にいいねしました" %>
      <% when 'comment' then %>
        <% if notification.post.user_id == visited.id %>
          <%= link_to "あなたの投稿", notification.post %>
        <% else %>
          <%= link_to post_path(notification.post) do %>
            <%= notification.post.user.name + 'さんの投稿'%>
          <% end %>
        <% end %>
        <%= "にコメントしました" %>
        <p class= "text-muted">
          <%= Comment.find_by(id: notification.comment_id)&.comment %>
        </p>
      <% end %>
    </div>
    <div class= "small text-muted text-right mt-3">
      <%= time_ago_in_words(notification.created_at).upcase %>
    </div>
  </div>
</div>

app/views/notifications/_notifications.html.erb
<% visitor = notification.visitor %>
<% visited = notification.visited %>
<div class= "col-md-6 mx-auto">
  <div class= "form-inline">
    <span>
      <%= link_to user_path(visitor) do %>
        <%= visitor.name %> <p>"さんが"</p>
      <% end %>
      <% case notification.action %>
      <% when 'follow' then %>
        <%= "あなたをフォローしました" %>
      <% when 'favorite' then %>
        <%= link_to 'あなたの投稿', notification.post %>
        <%= "にいいねしました" %>
      <% when 'comment' then %>
        <% if notification.post_id == visit.id %>
          <%= link_to "あなたの投稿", notification.post %>
        <% else %>
          <span>
            <%= link_to post_path(notigication.post) do %>
              <%= notification.post.user.name + 'さんの投稿'%>
            <% end %>
          </span>
        <%= "にコメントしました" %>
        <p class= "text-mited mb-0">
          <%= Comment.find_by(id: notification.comment_id)&.comment %>
        </p>
        <% end %>
      <% end %>
    </span>
    <div class= "small text-muted text-right">
      <%= time_ago_in_words(notification.created_at).upcase %>
    </div>
  </div>
</div>

app/views/notifications/index.html.erb
<% notifications = @notifications.where.not(visitor_id: current_user.id) %>
<div class= "container">
  <div class= "row">
    <div class= "col-12">
      <h2 class= "pt-4 text-secondary text-center font-weight-bold border-bottom">Notifications</h2>
      <div>
        <% if notifications.exists? %>
          <%= render notifications %>
        <% else %>
          <p class= "text-center">通知はありません</p>
        <% end %>
      </div>
    </div>
  </div>
</div>