config/routes.rb
Rails.application.routes.draw do
  resources :chats, only: [:show, :create]
  get 'users/:id/favorites' => 'users#favorites'
  get 'genres/show/:genre_id', to: 'genres#show', as: 'genre'
  get 'searches/search'
  devise_for :users
  root to: 'homes#top'
  get 'homes/top'
  get 'homes/about'

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as:  'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  resources :notifications, only: :index

  get '/search', to: 'searches#search'

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :name, presence: true, uniqueness: true, length: {minimum: 2, maximum: 20}
  validates :introduction, length: {maximum: 50}

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  #自分がフォローされる側の関係性
  has_many :reverse_of_relationships, foreign_key: "followed_id", class_name: "Relationship", dependent: :destroy
  #自分がフォローする側の関係性
  has_many :relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy

  #自分をフォローしている人(上記reverse_of_relationshipsを通じて参照)
  has_many :followers, through: :reverse_of_relationships, source: :follower
  #自分がフォローしている人(上記relationshipsを通じて参照)
  has_many :followings, through: :relationships, source: :followed
  has_many :user_rooms
  has_many :chats
  # リレーションとクラス名が異なるため、クラス名を明記
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def self.search_for(content, method)
    if method == 'perfect'
      User.where(name: content)
    elsif method == 'forward'
      User.where('name LIKE ?', content + '%')
    elsif method == 'backward'
      User.where('name LIKE ?', '%' + content)
    else
      User.where('name LIKE ?', '%' + content + '%')
    end
  end

  def create_notification_follow!(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ?", current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end

  has_one_attached :image
  validate :image_type

  private

  def image_type
    if image.attached?
      if !image.blob.content_type.in?(%('image/jpeg image/png'))
        image.purge # Rails6では、この1行は必要ない
        errors.add(:image, 'はJPEGまたはPNG形式を選択してアップロードしてください')
      end
    end
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]

  def index
    @users = User.page(params[:page]).per(10).reverse_order
  end

  def show
    @user = User.find(params[:id])
    @posts = Post.page(params[:page]).per(10).reverse_order
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "ユーザー情報の編集が完了しました"
    else
      render:edit
    end
  end

  def favorites
    @favorited_posts = Post.where(id: Favorite.where(user_id: current_user.id).pluck('post_id'))
  end

  private

  def user_params
    params.require(:user).permit(:name, :image, :introduction)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to users_path
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_loadimage.erb
<!--まだ100%理解できていない為JavaScriptの学習を進め復習する項目-->
<script>
  function loadImage(obj)
  {
    var allPreview = document.getElementById('user_images');
    var newPreview = document.createElement("p");
    allPreview.querySelector("p").remove();
    newPreview.setAttribute("id","preview");
    allPreview.insertBefore(newPreview, allPreview.firstChild);
    document.getElementById("user_images").style.display = "";
    for (i = 0; i < obj.files.length; i++) {
        var fileReader = new FileReader();
        fileReader.onload = (function (e) {
            var img = new Image();
            img.src = e.target.result;
            document.getElementById('preview').appendChild(img);
        });
      fileReader.readAsDataURL(obj.files[i]);
    }
  }
</script>

app/views/users/_users.html.erb
<div class= "col-12 d-flex flex-wrap">
  <% users.each do |user| %>
  <div class= "card mx-auto col-5 pt-3 pb-3 mt-4 mb-4 shadow">
    <%= link_to user_path(user.id) do %>
      <div class= "pl-3">
        <% if user.image.attached? %>
          <%= image_tag user.image, size: "400x400", class: "rounded-circle", alt: "Profile Image"%>
        <% else %>
          <%= image_tag 'no_image_profile.jpg', size: "400x400", class: "mx-auto rounded-circle"%>
        <% end %>
      </div>
      <h4 class= "font-weight-bold text-center"><%= user.name%></h4>
    <% end %>
    <div class= "d-flex justify-content-around">
      <p class= "mt-2 font-weight-bold">投稿件数 <%= user.posts.count %>件</p>
      <div class= "mt-2">
        Follows： <%= link_to user.followings.count, user_followings_path(user.id) %>
      </div>
      <div class= "mt-2">
        Followers: <%= link_to user.followers.count, user_followers_path(user.id) %>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class= "container">
  <div class= "row">
    <h2 class= "p-4 text-secondary font-weight-bold">プロフィール編集</h2>
  </div>
  <div class= "row">
    <div class= "col-lg-8">
      <% if @user.errors.any? %>
        <div id="error_explanation" class="alert alert-danger">
          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%= form_with model:@user,local:true do |f| %>
        <div class="field">
          <h4>名前</h4>
          <%= f.text_field :name, autofocus: true %>
        </div>
        <div class= "field pt-4">
          <h4>自己紹介</h4>
          <%= f.text_area :introduction, size: "60x10", placeholder: "あなたの英語力や語学学習歴を紹介しましょう。" %>
        </div>
        <div class= "field pt-4 mb-2">
          <h4>プロフィール画像</h4>
          <%= f.file_field :image, class: "push", onchange: "loadImage(this);" %>
        </div>
        <div id= "user_images" style= "display: none;">
          <p id= "preview" style= "height:60px;"></p>
        </div>
        <div class= "actions pt-4 pb-4">
          <%= f.submit "Save Profile", class: "btn btn-success" %>
        </div>
      <% end %>
      <%= render "loadimage" %>
    </div>
  </div>
</div>

app/views/users/favorites.html.erb
<div class= "container">
  <div class= "row">
    <div class= "col-12 border-bottom">
      <h2 class= "pt-4 text-secondary text-center font-weight-bold">Your Favorite Contents</h2>
    </div>
    <%= render 'posts/posts', posts: @favorited_posts %>
  </div>
</div>

app/views/users/index.html.erb
<div class= "container">
  <div class= "row">
    <div class= "col-12 border-bottom">
      <h2 class= "pt-4 text-secondary text-center font-weight-bold">All Users</h2>
    </div>
    <%= render 'users/users', users: @users %>
  </div>
</div>

app/views/users/show.html.erb
<div class= "container">
  <div class= "row border-bottom">
    <div class= "col-4 mt-4">
      <% if @user.image.attached? %>
        <%= image_tag @user.image, size: "300x300", alt: "Profile Image", class: "mx-auto rounded-circle" %>
      <% else %>
        <%= image_tag 'no_image_profile.jpg', size: "300x300", class: "mx-auto rounded-circle" %>
      <% end %>
    </div>
    <div class= "col-8 mt-4">
      <h2 class= "font-weight-bold"><%= @user.name %></h2>
        <% if @user.id == current_user.id %>
          <%= link_to "プロフィールを編集", edit_user_path(@user.id), class:"btn btn-secondary mb-2" %><br>
          <%= link_to "お知らせ", notifications_path, class:"btn btn-danger" %>
          <% if unchecked_notifications.any? %>
            <i class="fas fa-circle n-circle"></i>
          <% end %>
        <% else %>
          <div class= "follow-btn">
            <%= render "relationships/follow-btn", user: @user %>
          </div>
        <% end %>
      <div class= "follows-count">
        <%= render "relationships/count", user: @user %>
      </div>
      <h6 class= "font-weight-bold pt-4">自己紹介</h6>
      <p><%= @user.introduction %></p>
      <p class= "pt-3 font-weight-bold">投稿件数 <%= @user.posts.count %>件</p>
      <% if @user.id == current_user.id %>
        <%= link_to "Create New Post", new_post_path, class: "btn btn-success mb-2" %><br>
        <%= link_to "Your Favorite Contents", "/users/#{@user.id}/favorites", class: "btn btn-info mb-2" %><br>
      <% else %>
      <div class= "chat-btn">
        <%= render 'chats/chat-btn', user: @user %>
      </div>
      <% end %>
    </div>
  </div>
  <div class= row>
    <%= render 'posts/posts', posts: @user.posts %>
  </div>
</div>