config/routes.rb
Rails.application.routes.draw do
  resources :chats, only: [:show, :create]
  get 'users/:id/favorites' => 'users#favorites'
  get 'genres/show/:genre_id', to: 'genres#show', as: 'genre'
  get 'searches/search'
  devise_for :users
  root to: 'homes#top'
  get 'homes/top'
  get 'homes/about'

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as:  'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  resources :notifications, only: :index

  get '/search', to: 'searches#search'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord

  belongs_to :user
  belongs_to :room

  validates :message, presence: true, length: { maximum: 140 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  has_many :notifications, dependent: :destroy

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :posts, dependent: :destroy

end

app/models/notification.rb
class Notification < ApplicationRecord
  default_scope -> {order(created_at: :desc)}
  # nilを許可するための"optional: true"の記述
  belongs_to :post, optional: true
  belongs_to :comment, optional: true

  belongs_to :visitor, class_name: 'User', foreign_key: 'visitor_id', optional: true
  belongs_to :visited, class_name:'User', foreign_key: 'visited_id', optional: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :genre
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :notifications, dependent: :destroy

  validates :title, presence: true
  validates :description, presence: true
  validates :genre, presence: true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.search_for(content, method)
    if method == 'perfect'
      Post.where(title: content)
    elsif method == 'forward'
      Post.where('title LIKE ?', content + '%')
    elsif method == 'backward'
      Post.where('title LIKE ?', '%' + content)
    else
      Post.where('title LIKE ?', '%' + content + '%')
    end
  end

  def create_notification_favorite!(current_user)
    #いいねされているか判別
    temp = Notification.where(["visitor_id = ? and visited_id = ? and post_id = ? and action = ?", current_user.id, user_id, id, 'favorite'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        post_id: id,
        visited_id: user_id,
        action: 'favorite'
      )
      # 自分で行ういいねは通知済みとみなす
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end

  def create_notification_comment!(current_user, comment_id)
    # コメントしている人全員のid取得及び通知送信
    temp_ids = Comment.select(:user_id).where(post_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, comment_id, temp_id['user_id'])
    end
    # コメントなければ投稿者へ通知
    save_notification_comment!(current_user, comment_id, user_id) if temp_ids.blank?
  end

  def save_notification_comment!(current_user, comment_id, visited_id)
    # 複数のコメントを想定
    notification = current_user.active_notifications.new(
      post_id: id,
      comment_id: comment_id,
      visited_id: visited_id,
      action: 'comment',
    )
    # 自分の投稿へのコメントは通知済みとみなす
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end

  has_one_attached :image
  validate :image_type

  private

  def image_type
    if image.attached?
      if !image.blob.content_type.in?(%('image/jpeg image/png'))
        image.purge # Rails6では、この1行は必要ない
        errors.add(:image, 'はJPEGまたはPNG形式を選択してアップロードしてください')
      end
    end
  end

end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

end

app/models/room.rb
class Room < ApplicationRecord

  has_many :user_rooms
  has_many :chats

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :name, presence: true, uniqueness: true, length: {minimum: 2, maximum: 20}
  validates :introduction, length: {maximum: 50}

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  #自分がフォローされる側の関係性
  has_many :reverse_of_relationships, foreign_key: "followed_id", class_name: "Relationship", dependent: :destroy
  #自分がフォローする側の関係性
  has_many :relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy

  #自分をフォローしている人(上記reverse_of_relationshipsを通じて参照)
  has_many :followers, through: :reverse_of_relationships, source: :follower
  #自分がフォローしている人(上記relationshipsを通じて参照)
  has_many :followings, through: :relationships, source: :followed
  has_many :user_rooms
  has_many :chats
  # リレーションとクラス名が異なるため、クラス名を明記
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def self.search_for(content, method)
    if method == 'perfect'
      User.where(name: content)
    elsif method == 'forward'
      User.where('name LIKE ?', content + '%')
    elsif method == 'backward'
      User.where('name LIKE ?', '%' + content)
    else
      User.where('name LIKE ?', '%' + content + '%')
    end
  end

  def create_notification_follow!(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ?", current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end

  has_one_attached :image
  validate :image_type

  private

  def image_type
    if image.attached?
      if !image.blob.content_type.in?(%('image/jpeg image/png'))
        image.purge # Rails6では、この1行は必要ない
        errors.add(:image, 'はJPEGまたはPNG形式を選択してアップロードしてください')
      end
    end
  end


end

app/models/user_room.rb
class UserRoom < ApplicationRecord

  belongs_to :user
  belongs_to :room

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_search.html.erb
<div class= "search-form ml-4">
  <%= form_with url: search_path, method: :get, local: true do |f| %>
    <%= f.text_field :content %>
    <%= f.select :model, options_for_select({"User" => "user", "Post" => "post"}) %>
    <%= f.select :method, options_for_select({"完全一致" => "perfect", "前方一致" => "forward", "後方一致" => "backward", "部分一致" => "partial" }) %>
    <%= f.submit 'Search', class: "btn btn-primary" %>
    <i class="fas fa-search"></i>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LanguageLuggage</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/ff5426bf2c.js" crossorigin="anonymous"></script>
    <meta name= "viewport" content= "width=device-width, initial-scale=1, maximum-scale=1" >

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class= "d-flex flex-column vh-100">
    <header class= "shadow-sm bg-light">
      <nav class= "navbar navbar-expand-lg navbar-light">
        <div class= "container">
            <%= image_tag 'logo.jpg', class: "img-fluid", size: "50x50", alt: "LOGO" %>
          <h2 class= "text-black font-weight-bold">Language Luggage</h2>
          <button class= "navbar-toggler" type= "button" data-toggle= "collapse" data-target= "#navbarNavDropdown" aria-controls= "navbarNavDropdown" aria-expanded= "false" aria-label= "Toggle navigation">
            <span class= "navbar-toggler-icon"></span>
          </button>
          <div class= "collapse navbar-collapse" id= "navbarNavDropdown">
            <ul class= "navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li class= "nav-item">
                  <%= link_to "My Page", user_path(current_user.id), class: 'nav-link text-dark' %>
                </li>
                <li class= "nav-item">
                  <%= link_to "Users", users_path, class: 'nav-link text-dark' %>
                </li>
                <li class= "nav-item">
                  <%= link_to "Contents", posts_path, class: 'nav-link text-dark' %>
                </li>
                <li class= "nav-item">
                  <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'nav-link text-dark' %>
                </li>
                <li class= "nav-item">
                  <%= render 'layouts/search' %>
                </li>
              <% else %>
                <li class= "nav-item">
                  <%= link_to "Home", homes_top_path, class: 'nav-link text-dark' %>
                </li>
                <li class= "nav-item">
                  <%= link_to "About", homes_about_path, class: 'nav-link text-dark' %>
                </li>
                <li class= "nav-item">
                  <%= link_to "Sing Up", new_user_registration_path, class: 'nav-link text-dark' %>
                </li>
                <li class= "nav-item">
                  <%= link_to "Login", new_user_session_path, class: 'nav-link text-dark' %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class= "mb-auto">
      <p id="notice" class= "mt-3 ml-4 font-weight-bold text-success"><%= notice %></p>
      <%= yield %>
    </main>

    <footer class= "bg-dark text-white pt-3">
      <div class= "container">
        <div class= "row">
          <div class= "col-md-4">
            <p>Let's share your favorite stories.</p>
          </div>
          <div class= "col-md-4">
            <h6 class= "text-white">Language Luggage</h6>
          </div>
          <div class= "col-md-4">
            <p class = "text-white-50">Produced by<br>Tomo.T</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>